name: pull-requests

on:
  pull_request_target:
    branches: [master]
    types: [opened, edited, reopened, ready_for_review]

jobs:
  title:
    name: pr-title
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
